### ISSUE TITLE
When running test_dp_runner in sg2 script errors out

### ISSUE THREAD

**Issue by mudit70** [noironetworks/noirotest#1]
steps to reproduce
1. git clone from noirotest into gbpauto on controller
2. source keystonerc_admin
3. cd into gbpauto
4. source setup.sh
5. cd into testcases/testcases_dp
6. edit testconfig_def.yaml
7. run test_dp_runner.py with the testconfig_def.yaml as a parameter.

script runs but errors out with the following message:
--- 6.6.6.4 hping statistic ---
3 packets transmitted, 0 packets received, 100% packet loss
round-trip min/avg/max = 0.0/0.0/0.0 ms
root@test:~
Sent UDP packets
 hping3 6.6.6.4 --udp -p 443 -c 3 --fast -q
HPING 6.6.6.4 (eth0 6.6.6.4): udp mode set, 28 headers + 0 data bytes

--- 6.6.6.4 hping statistic ---
3 packets transmitted, 0 packets received, 100% packet loss
round-trip min/avg/max = 0.0/0.0/0.0 ms
root@test:~
2016-03-01 16:42:31,840 [INFO] testcases.testcases_dp.testsuite_diff_ptg_same_l2p_l3p - Results from the Testcase == {'6.6.6.4': {'udp': 0, 'icmp': 1, 'tcp': 0}}
2016-03-01 16:42:31,842 [ERROR] testcases.testcases_dp.testsuite_diff_ptg_same_l2p_l3p - Following traffic_types {'tcp': 0} = Failed
2016-03-01 16:42:31,842 [WARNING] testcases.testcases_dp.testsuite_diff_ptg_same_l2p_l3p - Repeat Run of the Testcase = test_5_traff_apply_prs_icmp_tcp
Traceback (most recent call last):
  File "test_dp_runner.py", line 69, in <module>
    main()
  File "test_dp_runner.py", line 52, in main
    testsuite.test_runner(log_string, location)
  File "/root/gbpauto/testcases/testcases_dp/testsuite_diff_ptg_same_l2p_l3p.py", line 90, in test_runner
    if test in test.__name__:
AttributeError: 'str' object has no attribute '__name__'
[root@sg2-controller testcases_dp(keystone_admin)]#

**Comment by mudit70** [comment]
Does not happen any more with latest master of noirotest.
