### ISSUE TITLE
test_dp_runner exits out at /root/gbpauto/testcases/testcases_dp/testsuite_diff_ptg_same_l2p_l3p.py", line 92, in test_runner

### ISSUE THREAD

**Issue by mudit70** [noironetworks/noirotest#2]
--- 6.6.6.4 hping statistic ---
3 packets transmitted, 0 packets received, 100% packet loss
round-trip min/avg/max = 0.0/0.0/0.0 ms
root@test:~
Results from the Testcase ==  {'6.6.6.4': {'udp': 0, 'icmp': 0, 'tcp': 0}}
2016-03-02 11:41:13,272 [INFO] testcases.testcases_dp.testsuite_diff_ptg_same_l2p_l3p - TEST_DIFF_PTG_SAME_L2P_L3P_VXLAN_IPV4_VPC_SAME_HOST_TEST_8_TRAFF_REM_PRS == PASS
Traceback (most recent call last):
  File "test_dp_runner.py", line 69, in <module>
    main()
  File "test_dp_runner.py", line 52, in main
    testsuite.test_runner(log_string, location)
  File "/root/gbpauto/testcases/testcases_dp/testsuite_diff_ptg_same_l2p_l3p.py", line 92, in test_runner
    gen_test_report(test_results, suite_name.upper(), 'a')
NameError: global name 'gen_test_report' is not defined

**Comment by mudit70** [comment]
Does not happen any more.
