### ISSUE TITLE
Script exits when timeout occurs in connecting from namespace to VM

### ISSUE THREAD

**Issue by mudit70** [noironetworks/noirotest#3]
When I run test_runner_dp in Fab 7, script exits with the following failure.  Need help analyzing, and we should likely exit more gracefully so that we get to cleanup stage before exit.

[10.30.120.105] out: tap1185c2ff-95: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
[10.30.120.105] out:         inet 7.7.1.2  netmask 255.255.255.0  broadcast 7.7.1.255
[10.30.120.105] out:         inet6 fe80::f816:3eff:fe95:2f08  prefixlen 64  scopeid 0x20<link>
[10.30.120.105] out:         ether fa:16:3e:95:2f:08  txqueuelen 0  (Ethernet)
[10.30.120.105] out:         RX packets 20  bytes 1624 (1.5 KiB)
[10.30.120.105] out:         RX errors 0  dropped 0  overruns 0  frame 0
[10.30.120.105] out:         TX packets 26  bytes 2092 (2.0 KiB)
[10.30.120.105] out:         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
[10.30.120.105] out: 
[10.30.120.105] out: 

2016-03-26 12:12:59,748 [INFO] testcases.testcases_dp.testsuite_diff_ptg_diff_l2p_same_l3p - 
Test_1_Traff_With_No_PRS 10 Traffic Sub-Testcases with NO CONTRACT for arp,dns,dhcp,udp,icmp and their combos
 hostname
fab7-compute-1.noiro.lab
[root@fab7-compute-1 ~]
6 ping 7.7.1.3 -c 2p-2e3f3f69-f48e-4b7b-b675-b4d180b3eac 
PING 7.7.1.3 (7.7.1.3) 56(84) bytes of data.
64 bytes from 7.7.1.3: icmp_seq=1 ttl=64 time=0.925 ms
64 bytes from 7.7.1.3: icmp_seq=2 ttl=64 time=0.184 ms

--- 7.7.1.3 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1000ms
rtt min/avg/max/mdev = 0.184/0.554/0.925/0.371 ms
[root@fab7-compute-1 ~]
Out ==NOIRO
Failing to Login into the VM from the Namespace

Exception Error: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x31b56d0>
command: /usr/bin/ssh
args: ['/usr/bin/ssh', 'root@10.30.120.105']
searcher: None
buffer (last 100 chars): ' ip netns exec qdhcp-2e3f3f69-f48e-4b7b-b675-b4d180b3eac \r6 ssh noiro@7.7.1.3\r\n'
before (last 100 chars): ' ip netns exec qdhcp-2e3f3f69-f48e-4b7b-b675-b4d180b3eac \r6 ssh noiro@7.7.1.3\r\n'
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 29909
child_fd: 13
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1

Failing to Login into the VM from the Namespace

Exception Error: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x31b56d0>
command: /usr/bin/ssh
args: ['/usr/bin/ssh', 'root@10.30.120.105']
searcher: None
buffer (last 100 chars): 'c \r6 ssh noiro@7.7.1.3\r\nip netns exec qdhcp-2e3f3f69-f48e-4b7b-b675-b4d180b3eac6 ssh noiro@7.7.1.3\r\n'
before (last 100 chars): 'c \r6 ssh noiro@7.7.1.3\r\nip netns exec qdhcp-2e3f3f69-f48e-4b7b-b675-b4d180b3eac6 ssh noiro@7.7.1.3\r\n'
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 29909
child_fd: 13
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1

**Comment by mudit70** [comment]
Here is the traceback...
Traceback (most recent call last):
  File "test_dp_runner.py", line 79, in <module>
    main()
  File "test_dp_runner.py", line 51, in main
    testsuite.test_runner(log_string, location)
  File "/root/gbpauto/testcases/testcases_dp/testsuite_diff_ptg_diff_l2p_same_l3p.py", line 83, in test_runner
    testresult = test()
  File "/root/gbpauto/testcases/testcases_dp/testsuite_diff_ptg_diff_l2p_same_l3p.py", line 178, in test_1_traff_with_no_prs
    return self.verify_traff()
  File "/root/gbpauto/testcases/testcases_dp/testsuite_diff_ptg_diff_l2p_same_l3p.py", line 141, in verify_traff
    results = gbppexptraff.test_run()
  File "/root/gbpauto/libs/gbp_pexp_traff_libs.py", line 69, in test_run
    child.expect('noiro:')
  File "/usr/lib/python2.7/site-packages/pexpect/spawnbase.py", line 315, in expect
    timeout, searchwindowsize, async)
  File "/usr/lib/python2.7/site-packages/pexpect/spawnbase.py", line 339, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/lib/python2.7/site-packages/pexpect/expect.py", line 104, in expect_loop
    return self.timeout(e)
  File "/usr/lib/python2.7/site-packages/pexpect/expect.py", line 68, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x31b56d0>
command: /usr/bin/ssh
args: ['/usr/bin/ssh', 'root@10.30.120.105']
searcher: None
buffer (last 100 chars): 'ot@fab7-compute-1 ~]# ip netns exec qdhcp-2e3f3f69-f48e-4b7b-b675-b4d180b3eac \r6 ssh noiro@7.7.1.3\r\n'
before (last 100 chars): 'ot@fab7-compute-1 ~]# ip netns exec qdhcp-2e3f3f69-f48e-4b7b-b675-b4d180b3eac \r6 ssh noiro@7.7.1.3\r\n'
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 29909
child_fd: 13
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1

**Comment by mudit70** [comment]
Figured out the issue -- master was not getting cloned properly.
